export { ChatContainer } from './ChatContainer'
export { ChatHeader } from './ChatHeader'
export { ChatMessages } from './ChatMessages'
export { BotMessage } from './BotMessage'
export { UserMessage } from './UserMessage'
export { TypingIndicator } from './TypingIndicator'
export { QuickReplyButtons } from './QuickReplyButtons'
export { ChatInput } from './ChatInput'
export { ChatUpload } from './ChatUpload'
export { ChatColorPicker } from './ChatColorPicker'
export { ChatLayout } from './ChatLayout'
export { ChatFunnel } from './ChatFunnel'

// Novos componentes UX Premium
export { ProgressBar, getProgressInfo } from './ProgressBar'
export { SocialProofBanner } from './SocialProofBanner'
export { ProjectTypeCard, ProjectTypeCards, PROJECT_TYPES } from './ProjectTypeCard'
export { ProjectSummary } from './ProjectSummary'
export { CelebrationEffect, useCelebration } from './CelebrationEffect'
